### ISSUE TITLE
example

### ISSUE THREAD

**Issue by fixopen** [fixopen/study#1]
提出问题，赋予责任人
@githubHss 通过@name去提醒责任人查看
责任人修改了该问题后，由提出问题的人关闭问题

可以加labels，加milestone。

这是一个例子，责任人试着回复它

**Comment by githubHss** [comment]
ok,get it

**Comment by fixopen** [comment]
@githubHss 用这种方式提请对方注意。比如，你用 @fixopen ，会导致github给我一个提醒，我就会有所觉察了。

**Comment by githubHss** [comment]
@fixopen 嗯嗯，知道了。
